version: '3.8'

services:
  notes-app:
    build: .
    ports:
      - "3000:3000"  # tRPC/database server
      - "80:80"  # SvelteKit website server
    volumes:
      - ./notes.db:/app/notes.db  # Persist SQLite database
    environment:
      - NODE_ENV=production
      - PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s